swagger: 2.0
openapi: 3.0.0
info:
  description: Example of Swagger
  version: 1.0.0
  title: Swagger Demo
schemes:
  - http
basePath: "/api/v1"
tags:
- name: Users
  description: Everything about user
paths:
  /users:
    post:
      tags:
      - Users
      summary: Add new user
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: data
        description: New user info
        schema:
          type: object
          properties:
            name:
              type: string
              example: User 1
            password:
              type: string
              example: "12345678"
    #  responses:
    #    200:
    #      description: Create user success
    #      schema:
    #        type: object
    #        properties:
    #          name:
    #            type: string
    #            example: User 1
    #    400:
    #      description: Create user fail
    #      schema:
    #        type: object
    #        properties:
    #           errors:
    #           type: string
    #           example: Some thing went wrong